name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION="122.0.4"
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Print Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Start Server with xvfb
        run: xvfb-run --auto-servernum npm start & npx wait-on --timeout 120000 http://localhost:4200/

      - name: Run Unit Tests
        run: SERVE_PORT=4200 npm run ionic-e2e:develop -- --headless
